### ISSUE TITLE
[BUG] `no-custom-classname` is super slow 🐢

### ISSUE THREAD

**Issue by B2o5T** [francoismassart/eslint-plugin-tailwindcss#174]
**Describe the bug**
Rule                                    | Time (ms) | Relative
:---------------------------------------|----------:|--------:
tailwindcss/no-custom-classname         | 13424.990 |    68.8%
@typescript-eslint/no-floating-promises |  3580.858 |    18.4%
tailwindcss/no-contradicting-classname  |   565.713 |     2.9%
import/no-self-import                   |   513.516 |     2.6%
tailwindcss/enforces-shorthand          |   435.607 |     2.2%
import/no-extraneous-dependencies       |   260.153 |     1.3%
@typescript-eslint/no-unused-vars       |   216.892 |     1.1%
react/no-direct-mutation-state          |    50.211 |     0.3%
hive/enforce-deps-in-dev                |    44.395 |     0.2%
simple-import-sort/imports              |    30.109 |     0.2%

**Environment (please complete the following information):**
eslint-plugin-tailwindcss: 3.6.2

**eslint config file or live demo**
[By providing a link to a live demo, a demo video or a github repo fixing the issue will be easier.](https://github.com/kamilkisiela/graphql-hive/blob/9e81130c12a4bf26b4a2f537e823ad9cbcbc5d9c/.eslintrc.cjs#L119)

**Comment by francoismassart** [comment]
Hi,
This could be caused by the number of css files to be parsed. 
Do you use a lot of CSS files ? Do you need them for whitelisting ? 
Maybe you can try setting the option as an empty array

https://github.com/francoismassart/eslint-plugin-tailwindcss/blob/master/docs/rules/no-custom-classname.md#cssfiles-default-css-node_modules--dist-build

If you see a positive impact maybe you should provide a narrower set of globs to be parsed by the rule. 

Let me know how it goes. 

I don’t have access to my computer for few days.

**Comment by francoismassart** [comment]
👋  @B2o5T 

Can you try adding this extra param inside `.eslintrc.cjs` line 86, right after `config: 'packages/app/tailwind.config.js',`:

```js
          cssFiles: [
            'packages/web/app/src/**/*.css',
            '!packages/web/app/public/styles.css',
          ],
```

This should limit the workload of the CSS parsing to only browse `packages/web/app/src/` and its sub directories while avoiding to go "inception" style by browsing the generated Tailwind CSS declarations...

Let me know if it helps

**Comment by B2o5T** [comment]
@francoismassart thanks for your response, seems like our problem is not due `no-custom-classname` rule, but due rules from` typescript-eslint `plugin that requires types information
