### ISSUE TITLE
[Feature request] no-dynamic-classnames

### ISSUE THREAD

**Issue by rebelchris** [francoismassart/eslint-plugin-tailwindcss#181]
**Is your feature request related to a problem? Please describe.**
It's not recommended to use dynamic classNames for examples `<div class="text-{{ error ? 'red' : 'green' }}-600"></div>
`
Instead one should always use fully qualified as: `<div class="{{ error ? 'text-red-600' : 'text-green-600' }}"></div>`

**Describe the solution you'd like**
Not quite sure which part we could tap into to make it work better.

**Describe alternatives you've considered**
Custom rule.

**Additional context**
[Additional information on Tailwind docs](https://tailwindcss.com/docs/content-configuration#dynamic-class-names)

**Comment by francoismassart** [comment]
Hi @rebelchris,
Hope my first sponsor is doing well 😉 

Kind of a late response but here it is anyway.

I believe this case is already covered by the `no-custom-classname` rule.

But the plugin does not parse your snippet because of its syntax: 

- you declare the class attribute as a simple string (`Literal`)
- but this literal string contains an expression meant to be interpreted
- I'm not even sure the parser can digest this

I would recommend you to use this kind of syntax instead which will be parse by `eslint-plugin-tailwindcss`:

```jsx
<div className={`text-${ error ? 'red' : 'green' }-600`}>no-dynamic-classnames demo</div>
``` 

This snippet will cause 4 lint errors from `no-custom-classname`:

- `red`
- `green`
- `text-`
- `-600`

I tested this on my local:
<img width="700" alt="image" src="https://user-images.githubusercontent.com/704026/231508255-a2cb2915-c141-4c2a-9576-35be067eeddb.png">

<img width="706" alt="image" src="https://user-images.githubusercontent.com/704026/231508360-bfdc4e2c-4def-4f85-b95c-a80ea58e6f1b.png">


WDYT ? Let me know but I guess I can close this one...

**Comment by kueda** [comment]
FWIW, two advantages of making this an additional rule:

1. It would make it clearer to the developer what was wrong; the problem this is trying to prevent is not custom classes but dynamic classes, so if I enter a class like
    ```
    `text-${ error ? 'red' : 'green' }-600`
    ```
    I know that should get interpolated as one of two legitimate class names, so telling me I'm using a custom class is confusing.
1. It would allow different levels for the two different rules, e.g. `no-custom-classname` could be a warning but `no-dynamic-classnames` could be an error.
