### ISSUE TITLE
[Feature request] Support SASS

### ISSUE THREAD

**Issue by eIiot** [francoismassart/eslint-plugin-tailwindcss#206]
**Is your feature request related to a problem? Please describe.**
Currently, custom styles aren't showing up when using NextJS & `.scss` files. They can't be parsed as normal CSS, and so I doubt they would work with the plugin. It would be great if I didn't have to `// eslint-disable-next-line tailwindcss/no-custom-classname` for so many classes.

**Describe the solution you'd like**
Support `.scss` or "Sass" files.

**Comment by francoismassart** [comment]
Hi @eIiot ,
What if you configure the `eslint-plugin-tailwindcss` to parse the output CSS built by your SASS compilation ?
That could solve your issues.

Personally, when using Tailwind CSS, I tend to avoid writing custom CSS as much as possible, when I have no choice, I do write some CSS declarations in tiny CSS modules which the plugin can parse.

An other solution would be to use a custom prefix inside your SCSS declaration and whitelist them all using a regex which accepts all the classnames starting with your custom prefix.

Parsing the CSS is by far the most time consuming inner task executed by the plugin and parsing SCSS file can be very tricky due to the huge possibilities/features of SASS.

If anyone is up to the challenge and has a well set up plan for this feature, you're welcome to contribute but I've no plan do it myself.

WDYT?

Cheers.

**Comment by eiiot** [comment]
I'm currently compiling SASS with Next.js, which means there aren't any output files to point to! :(

I'll look into the regex option, although this would still be nice to have at some point! Maybe I can contribute :)

Thanks for the quick response!

**Comment by francoismassart** [comment]
You just need to add a new script entry in your package.json which will watch and compile your SCSS files to a temporary location then…
