### ISSUE TITLE
[Feature request] Linting in regular string with variable name regex

### ISSUE THREAD

**Issue by dante-sparras** [francoismassart/eslint-plugin-tailwindcss#225]
**Is your feature request related to a problem? Please describe.**
I would like to get linting working in regular strings depending on the variable name. For example, I'm using variables with the suffix 'Styles'.

```
const divStyles = 'flex h-10 w-10 items-center';
```

**Describe the solution you'd like**
An option in the eslint file to a lint a string assigned to a variable of matching regex.
```
settings: {
    tailwindcss: {
       variableRegex: ".*Styles*"
    },
  },
```

**Comment by francoismassart** [comment]
Hi @dante-sparras,

This kind of behavior already exists in the plugin, you can use a `callee` which is a registered function that will trigger the plugin:

e.g. 
```js
import ctl from "@netlify/classnames-template-literals";
...
const divStyles = ctl('flex h-10 w-10 items-center');
```

or you can use a **tagged template literal** expression like:

```js
const divStyles = tw`flex h-10 w-10 items-center`;
```

if you set the `tags` setting https://github.com/francoismassart/eslint-plugin-tailwindcss#more-settings

```js
...
tags: ['tw'],
...
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

Because there are already these 2 ways of doing it, I won't implement a third way.

If you need more help on this, share a demo repository and I'll help you out.
