### ISSUE TITLE
[BUG] Warning: Classname 'font-mono' is not a Tailwind CSS class!

### ISSUE THREAD

**Issue by tellaconz** [francoismassart/eslint-plugin-tailwindcss#65]
**Describe the bug**
24:17  Warning: Classname 'font-mono' is not a Tailwind CSS class!

Getting this warning, the font is being displayed fine and should be valid tailwindcss I believe?

**Comment by francoismassart** [comment]
👋  @tellaconz ,
I did try to reproduce the issue but I did not get an error...

I did add a test case:
![image](https://user-images.githubusercontent.com/704026/141362496-286a50ae-677c-4013-8c3a-717740772774.png)

And it is passing:
![image](https://user-images.githubusercontent.com/704026/141362567-0c0f499c-0ddf-4378-89fd-592950fa3cfb.png)

![image](https://user-images.githubusercontent.com/704026/141362640-db8e7b6f-092b-4990-88b9-7b99cdc27bf8.png)


Please re-open the issue when you can provide a dummy project demonstrating the issue so that I can clone it and debunk the issue from there.

**Comment by francoismassart** [comment]
https://github.com/francoismassart/eslint-plugin-tailwindcss/commit/a3aa5ce953178ee8e688c87925a31b0d3cb6c915
