### ISSUE TITLE
[Feature request] Support TailwindCSS v3.0

### ISSUE THREAD

**Issue by TheoBr** [francoismassart/eslint-plugin-tailwindcss#69]
[Tailwind CSS v3.0 just dropped!](https://tailwindcss.com/blog/tailwindcss-v3)

Would be great to get this plugin up to the latest version of Tailwind. There's a small handful of things that aren't linting correctly for us, including:
- Anything using JIT syntax (since `mode: "jit"` is deprecated, jit mode isn't triggered)
- [`overflow` text rules becoming `text` prefixed ](https://tailwindcss.com/docs/upgrade-guide#overflow-clip-ellipsis)

Haven't had a chance to look at source but I'm potentially down to contribute 👀

**Comment by francoismassart** [comment]
Hi @TheoBr, thank you for your support, I'll definitively work on supporting v3.0 of TailwindCSS.
I already started reading the documentation last night.
Some of the changes looks challenging, especially the [ordering-stacked-modifiers](https://tailwindcss.com/docs/hover-focus-and-other-states#ordering-stacked-modifiers) but I'll do my best. 💪 

The plugin's version will increase its major to 3, matching Tailwind CSS' major version.

**Comment by kiliw** [comment]
Sounds great, I would love to see an upgrade.

I currently have a problem with storybook and tailwind, which sounds not related to the plugin but I still want to share my observation.
Currently, I use `storybook 6.4.9` and `tailwind 3` and in my nextJs project, all works fine (styles are applied). Unfortunately, if I run the storybook the styles do not apply.
If I uninstall `eslint-plugin-tailwindcss` everything works fine and I figured that the plugin has tailwind ^2 as a dependency. So I assume I end up with two different versions of tailwind. Maybe I just configured something wrong but I just want to mention it here since all works fine if I uninstall the plugin.

**Comment by francoismassart** [comment]
You can try out the latest beta version which is compatible with TailwindCSS 3 via:

`npm i eslint-plugin-tailwindcss@3.0.0-beta.0 --save-dev`

Beware of the following:

- The **classname order** will probably change matching the new order of the [TailwindCSS 3 documentation](https://tailwindcss.com/docs/aspect-ratio)
- You will get errors on obsolete classnames (changed or gone in TW3) like:
  - `transform`, `filter`, `bg-opacity`... which are gone in v3
  - `placeholder-color` => `placeholder:text-color`
  - `flex-grow/shrink` => `grow/shrink`

Please give beta 0 a try and give me some feedback 😉

**Comment by kiliw** [comment]
@francoismassart Thanks a lot that worked. :+1: The styling of our storybook is again the same as the rest. :tada:

**Comment by ethanve** [comment]
@francoismassart thanks for all your hard work on this package. Started testing out the v3 beta and seeing that the opacity modifier isn't working for me (see https://tailwindcss.com/docs/ring-color#changing-the-opacity for an example)

**Comment by francoismassart** [comment]
@ethanve thank you for the feedback, it will be fixed soon in beta.1

**Comment by francoismassart** [comment]
@ethanve please give it a try with
`npm i eslint-plugin-tailwindcss@3.0.0-beta.1 --save-dev`

Changelog between beta.0 and beta.1:
- FIX missing opacity suffix modifier
- TESTS for colors + opacity

Ironically, I've less available time during holidays. I was supposed to enjoy a full week of personal time but school was closed one week too early due to COVID and parenting goes first 😅

**Comment by francoismassart** [comment]
Working on a migrating rule too, from v2 to v3

**Comment by francoismassart** [comment]
Version 3.0.0 is out, I hope you like it, ready to read more issues on github 😉
